quotes:
- "Be a yardstick of quality. Some people aren't used to an environment where excellence is expected. Steve Jobs"
- "Quality is more important than quantity. One home run is much better than two doubles. Steve Jobs."
- "I never think of the future. It comes soon enough. Albert Einstein."
- "Everything should be made as simple as possible, but not simpler. Albert Einstein."
- "Choose a job you love, and you will never have to work a day in your life. Confucius."
- "Our greatest glory is not in never falling, but in rising every time we fall. Confucius."